spring:
  application:
    name: notifyx

  profiles:
    active: email

  datasource:
    url: jdbc:h2:mem:notifyx
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

logging:
  level:
    root: INFO
    com.navesh.notifyx: DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    path: /swagger-ui
    operationsSorter: method
    tagSorter: alpha